# Generated by Django 3.2.6 on 2021-08-09 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('code', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('club', models.ManyToManyField(blank=True, to='matchingapp.Club')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_country', to='matchingapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_on', models.DateField(default=datetime.datetime.now)),
                ('contract_img', models.FileField(upload_to='')),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='club_membership', to='matchingapp.club')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_membership', to='matchingapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_country', to='matchingapp.country'),
        ),
    ]
