# Generated by Django 3.2.6 on 2021-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='clubs',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(blank=True, related_name='club_player', through='matchingapp.Membership', to='matchingapp.Club'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='contract_img',
            field=models.FileField(upload_to=''),
        ),
    ]
