# Generated by Django 3.2.6 on 2021-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AddField(
            model_name='player',
            name='membership',
            field=models.ManyToManyField(blank=True, to='matchingapp.Membership'),
        ),
    ]
